[local]
ip=127.0.0.1
port=9100
data_path=data
event_dispatcher_num=1
#auto_redirect=true

[store]
eloq_store_open_files_limit=256
eloq_store_cloud_endpoint=http://127.0.0.1:9900
eloq_store_cloud_store_path=dss-eloqsql-mtr-test/eloqstore
eloq_store_cloud_access_key=minioadmin
eloq_store_cloud_secret_key=minioadmin
