[local]
ip=127.0.0.1
port=9100
data_path=data
event_dispatcher_num=1
#auto_redirect=true

[store]
rocksdb_cloud_bucket_prefix=dss-
rocksdb_cloud_bucket_name=eloqsql-mtr-test
rocksdb_cloud_s3_endpoint_url=http://127.0.0.1:9900
aws_access_key_id=XXXXXXXXXXXXXXXXX
aws_secret_key=XXXXXXXXXXXXXXXXXXXXXXXX
