resources:
- name: eloqsql_src
  type: git
  check_every: 3m
  source:
    branch: merge
    uri: git@github.com:eloqdata/eloqsql.git
    private_key: ((git-key))

- name: eloq_test_src
  type: git
  source:
    branch: main
    uri: git@github.com:eloqdata/eloq-test.git
    private_key: ((git-key))

- name: eloq_ubuntu_2404
  type: registry-image
  source:
    repository: eloqdata/eloq-dev-ci-ubuntu2404
    tag: latest

jobs:
- name: compile-test
  build_log_retention:
    builds: 500
  serial: true
  plan:
  - in_parallel:
      steps:
      - get: eloqsql_src
        trigger: true
      - get: eloq_test_src
        trigger: true
      - get: eloq_ubuntu_2404
  - task: compile-test-task
    image: eloq_ubuntu_2404
    file: eloqsql_src/concourse/tasks/main.yml
    params:
      ELOQ_AWS_ACCESS_KEY_ID: ((minio-access-key))
      ELOQ_AWS_REGION: ((aws-region))
      ELOQ_AWS_SECRET_KEY: ((minio-secret-key))
      MINIO_ENDPOINT_URL: ((minio-endpoint))
    privileged: true
