platform: linux
image_resource:
  type: registry-image
inputs:
  - name: eloqsql_src
  - name: logservice_src
  - name: raft_host_manager_src
outputs:
  - name: the-output
params:
  LD_LIBRARY_PATH: /usr/local/lib:/usr/local/lib64
run:
  path: /bin/bash
  args:
    - eloqsql_src/concourse/scripts/build_tarball.bash