platform: linux
image_resource:
  type: registry-image
inputs:
  - name: eloqsql_pr
  - name: eloq_test_src
  - name: raft_host_manager_src
  - name: logservice_src
run:
  path: eloqsql_pr/concourse/scripts/pr.ent.bash
